# Config file for automatic testing at travis-ci.org

language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install -r requirements_dev.txt
  - pip install -r requirements.txt
  - pushd ..
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install enum34; fi
  - pip install codecov
  - popd
  - python setup.py build_ext --inplace

script:
  - py.test --cov
  - make lint

after_success:
  - bash <(curl -s https://codecov.io/bash)
