# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.4
  - 3.5

install:
  - pip install -r requirements_dev.txt
  - pip install -r requirements.txt
  - pip install codecov
  - python setup.py build_ext --inplace

script:
  - py.test --cov
  - make lint

after_success:
  - bash <(curl -s https://codecov.io/bash)
